<?php
session_start();

// Priority: GET param > session > cookie > default AR
if (isset($_GET['lang']) && in_array($_GET['lang'], ['ar', 'en'])) {
    $_SESSION['lang'] = $_GET['lang'];
    setcookie('flex_lang', $_GET['lang'], time() + (365 * 24 * 3600), '/', '', false, false);
} elseif (!isset($_SESSION['lang'])) {
    // Read from cookie (set by JS AJAX switch)
    $cookieLang = $_COOKIE['flex_lang'] ?? 'ar';
    $_SESSION['lang'] = in_array($cookieLang, ['ar','en']) ? $cookieLang : 'ar';
}
$lang = $_SESSION['lang'];
$isAr = ($lang === 'ar');
$dir  = $isAr ? 'rtl' : 'ltr';
$fontClass = $isAr ? 'font-cairo' : 'font-poppins';

function t(string $key): string {
    global $lang;
    $translations = getTranslations();
    return $translations[$lang][$key] ?? $key;
}

function getTranslations(): array {
    return [
        'ar' => [
            // Nav
            'home'          => 'الرئيسية',
            'about'         => 'من نحن',
            'portfolio'     => 'أعمالنا',
            'services'      => 'خدماتنا',
            'gallery'       => 'ألبوم الصور',
            'contact'       => 'تواصل معنا',
            'startProject'  => 'ابدأ مشروعك',
            'exploreWork'   => 'استعرض أعمالنا',
            'contactUs'     => 'تواصل معنا',
            'contactInfoTitle' => 'معلومات التواصل',
            // Stats
            'statsProjects' => 'مشروع ناجح',
            'statsClients'  => 'عميل راضٍ',
            'statsYears'    => 'سنوات خبرة',
            'statsTeam'     => 'براند يثق بنا',
            // Why us
            'whyUsTitle'    => 'لماذا تختار فلكس؟',
            'whyUsSubtitle' => 'نجمع بين الإبداع اللامحدود والخبرة العميقة في السوق السعودي لنقدم نتائج تتجاوز التوقعات.',
            'competitiveBadge' => 'ميزتنا التنافسية',
            'whyF1T' => 'خبرة أكثر من 11 عاماً',
            'whyF1D' => 'منذ 2015م ونحن نعمل مع شركات من المنطقة الشرقية والرياض وعموم المملكة.',
            'whyF2T' => 'أفكار خارج الصندوق',
            'whyF2D' => 'نتحدى القوالب التقليدية ونبتكر حلولاً إعلانية لم يسبق تصورها.',
            'whyF3T' => 'التسليم في الموعد دائماً',
            'whyF3D' => 'نلتزم بالمواعيد النهائية دون التنازل عن الجودة أو الدقة في التفاصيل.',
            'whyF4T' => 'جودة المواد لا تُساوَم',
            'whyF4D' => 'نختار أجود خامات الطباعة واللافتات والتشطيبات — لأن كل تفصيل يعكس علامتك التجارية.',
            'whyF5T' => 'تصميم وتصنيع وتركيب',
            'whyF5D' => 'كل مراحل المشروع تحت سقف واحد — من أول رسم تصميمي حتى آخر مسمار في الموقع.',
            'whyF6T' => 'حضور ميداني فعلي',
            'whyF6D' => 'فريقنا يصل إليك في موقع المشروع — نقيس ونخطط ونشرف على التركيب بأنفسنا.',
            // CTA
            'ctaTitle'   => 'مستعد لإحداث ضجة؟',
            'ctaSubtitle'=> 'لنتحدث عن مشروعك القادم وكيف يمكننا تحويله إلى قصة نجاح.',
            'startNow'   => 'ابدأ الآن',
            // Services section labels
            'servicesTitle'    => 'ماذا نقدم؟',
            'servicesSubtitle' => 'مجموعة متكاملة من الخدمات الإعلانية والإبداعية مصممة لرفع قيمة علامتك التجارية وجعلها تتصدر المنافسة.',
            'viewAll'          => 'عرض كل الخدمات',
            'portfolioTitle'   => 'أعمالنا البارزة',
            'portfolioSubtitle'=> 'بعض من المشاريع التي نفتخر بها. نضع لمستنا السحرية في كل تفصيل.',
            'viewGallery'      => 'تصفح المعرض الكامل',
            // About page
            'aboutBadge'    => 'قصة فلكس',
            'aboutHero1'    => 'من نحن؟',
            'aboutHero2'    => 'وكالة تصنع الفارق',
            'aboutHeroDesc' => 'تأسست وكالة فلكس عام 2015م في مدينة الدمام، وحققت الوكالة خلال السنوات الأخيرة نمواً وتطوراً كبيراً في أعمالها ونشاطاتها وخدماتها في جميع المجالات الإعلانية.',
            'storyTitle'     => 'حكاية نجاح',
            'storyHighlight' => 'حقيقية',
            'storyP1' => 'تأسست وكالة فلكس للدعاية والإعلان عام 2015م في مدينة الدمام بالمملكة العربية السعودية، وتغطي أعمال الوكالة حالياً جميع مناطق المملكة العربية السعودية.',
            'storyP2' => 'وقد نفذت الوكالة عدداً من المشاريع والحملات الإعلانية، كما قامت بتنظيم العديد من المهرجانات والحفلات في المنطقة الشرقية وخارجها، وبفضل الله أولاً ثم بمجهودات جبارة من الطاقم الفني والإداري تمكنت الوكالة في وقت قياسي من تحقيق العديد من النجاحات والإنجازات الهامة.',
            'storyP3' => 'وتركت بصمة مميزة لدى عملائها وذلك من خلال القيم العالية التي تقوم عليها سياسة الوكالة في خدمة عملائها، عن طريق الالتزام بالمصداقية والأمانة في جميع تعاملاتها وباعتماد أعلى معايير الجودة في جميع الأعمال.',
            'statFounded' => 'سنة التأسيس',
            'statProjects'=> 'مشروع منجز',
            'statClients' => 'عميل راضٍ',
            'statRegions' => 'مناطق مغطاة',
            'statYears'   => 'سنة خبرة',
            'visionLabel' => 'OUR VISION',
            'visionTitle' => 'رؤيتنا',
            'visionText'  => 'رؤيتنا في وكالة فلكس أن نكون أحد الوكالات الرائدة في تقديم الحلول التسويقية والخدمات الإعلانية المبتكرة، وأن نكون سباقين في تقديم جميع خدمات الطباعة الحديثة بتقنيات متطورة وفائقة الجودة، وأن نقدم أرقى الخدمات لعملائنا داخل المملكة العربية السعودية وخارجها.',
            'missionLabel'=> 'OUR MISSION',
            'missionTitle'=> 'رسالتنا',
            'missionText' => 'نسعى دائماً في فلكس لتقديم أفضل جودة في الخدمات والإعلانات للوصول إلى أعلى مستويات رضا العملاء. لتحقيق أهدافنا، نستخدم أحدث وأكثر التقنيات ابتكاراً في معدات الطباعة، ونختار أجود المواد، ونؤكد على المعايير والمواصفات المعتمدة في المملكة العربية السعودية.',
            'valuesTitle'    => 'قيمنا',
            'valuesHighlight'=> 'الجوهرية',
            'valuesSubtitle' => 'هذه القيم هي الأساس الذي تقوم عليه سياستنا في خدمة عملائنا.',
            'v1T' => 'المصداقية والأمانة',        'v1D' => 'نلتزم بالصدق الكامل في جميع تعاملاتنا مع عملائنا وشركائنا.',
            'v2T' => 'أعلى معايير الجودة',        'v2D' => 'نعتمد أعلى معايير الجودة في جميع الأعمال دون أي تنازل.',
            'v3T' => 'الالتزام بالمواعيد',       'v3D' => 'نلتزم بالمواعيد المتفق عليها ونسعى دائماً للتسليم في الوقت المحدد.',
            'v4T' => 'رضا العملاء أولاً',         'v4D' => 'نضع رضا عملائنا في مقدمة أولوياتنا ونسعى لتجاوز توقعاتهم.',
            'v5T' => 'الابتكار المستمر',          'v5D' => 'نواكب أحدث التقنيات والتوجهات العالمية في صناعة الإعلان.',
            'v6T' => 'التغطية الشاملة',           'v6D' => 'نغطي جميع مناطق المملكة العربية السعودية لخدمة كل عملائنا.',
            'officesTitle'    => 'مكاتبنا',
            'officesHighlight'=> 'في المملكة',
            'office1City'  => 'الدمام', 'office1Desc' => 'المقر الرئيسي — المنطقة الشرقية', 'office1Badge' => 'المقر الرئيسي',
            'office2City'  => 'الرياض', 'office2Desc' => 'مكتب الرياض — المنطقة الوسطى',    'office2Badge' => 'فرع الرياض',
            'aboutCtaTitle'=> 'جاهز للعمل معنا؟',
            'aboutCtaDesc' => 'دعنا نتحدث عن مشروعك القادم ونقدم لك حلاً إعلانياً يحقق أهدافك.',
            'aboutCtaBtn'  => 'تواصل معنا',
            // Services page
            'servicesBadge'       => 'ما نقدمه',
            'servicesPageTitle'   => 'خدماتنا',
            'servicesPageHighlight'=> 'الإبداعية',
            'servicesPageDesc'    => 'نقدم في فلكس حزمة شاملة من خدمات الدعاية والإعلان والطباعة والتصنيع، نستخدم أحدث التقنيات وأجود المواد وفق المعايير المعتمدة في المملكة العربية السعودية.',
            'workshopTitle'       => 'ورشة التصنيع',
            'workshopHighlight'   => 'المتكاملة',
            'workshopDesc'        => 'نصنع جميع أنواع اللوحات الإعلانية بأعلى جودة وأحدث تقنيات التصنيع.',
            'workshopBtn'         => 'اطلب عرض سعر',
            'w1' => 'لوحات فلكس فيس',   'w2' => 'لوحات اليونيبول',    'w3' => 'لوحات الأحرف المجسمة',
            'w4' => 'وجهات الكلادينج', 'w5' => 'لوحات البنر',         'w6' => 'استيكر السيارات',
            'servicesCtaTitle'=> 'جاهز للخطوة القادمة؟',
            'servicesCtaDesc' => 'دعنا نعمل معاً لتحويل أفكارك إلى حملة إعلانية تتحدث عنها السوق.',
            'servicesCtaBtn'  => 'اطلب عرض سعر',
            // Contact page
            'contactBadge'    => 'نحن هنا للاستماع',
            'contactHero1'    => 'تواصل',
            'contactHero2'    => 'معنا',
            'contactHeroDesc' => 'شاركنا رؤيتك وسنقوم بتحويلها إلى واقع يفوق توقعاتك. فريقنا جاهز للرد على استفساراتك.',
            'contactDammam'       => 'الدمام — المقر الرئيسي',
            'contactDammamRegion' => 'المنطقة الشرقية، المملكة العربية السعودية',
            'contactRiyadh'       => 'الرياض — فرع',
            'contactRiyadhRegion' => 'المنطقة الوسطى، المملكة العربية السعودية',
            'contactHoursDays'    => 'الأحد — الخميس',
            'contactHoursTime'    => '9:00 صباحاً — 6:00 مساءً',
            'formTitle'   => 'أرسل لنا رسالة',
            'formName'    => 'الاسم الكامل',
            'formPhone'   => 'رقم الهاتف',
            'formEmail'   => 'البريد الإلكتروني',
            'formOptional'=> '(اختياري)',
            'formMessage' => 'تفاصيل المشروع أو الاستفسار',
            'formNamePh'  => 'أدخل اسمك',
            'formMsgPh'   => 'أخبرنا عن مشروعك أو ما تحتاجه...',
            'formSubmit'  => 'إرسال الرسالة',
            'formSending' => 'جاري الإرسال...',
            'formSuccess' => 'تم إرسال الرسالة وسيتم التواصل معكم قريباً',
            'formError'   => 'حدث خطأ، يرجى المحاولة مرة أخرى.',
            'sendAnother' => 'إرسال رسالة أخرى',
            // Footer
            'footerBio'          => 'تأسست وكالة فلكس للدعاية والإعلان عام 2015م في مدينة الدمام. وتغطي أعمال الوكالة جميع مناطق المملكة العربية السعودية بأعلى معايير الجودة والاحترافية.',
            'footerQuickLinks'   => 'روابط سريعة',
            'footerServicesTitle'=> 'خدماتنا',
            'footerContactTitle' => 'تواصل معنا',
            'footerCopyright'    => 'فلكس للدعاية والإعلان — جميع الحقوق محفوظة.',
            'fs1' => 'الطباعة الرقمية', 'fs2' => 'الهوية المؤسسية', 'fs3' => 'إدارة الفعاليات',
            'fs4' => 'التصميم 3D',      'fs5' => 'استيكر السيارات', 'fs6' => 'ورشة التصنيع',
            'fs7' => 'تصنيع اللوحات الإعلانية', 'fs8' => 'استاندات العرض الاحترافية',
            // Gallery
            'galleryPageTitle'    => 'ألبوم',
            'galleryPageHighlight'=> 'المشاريع',
            'galleryPageDesc'     => 'صور حقيقية من أعمالنا المنفذة — طباعة، تصنيع، فعاليات، هويات مؤسسية وأكثر.',
            'filterAll'           => 'الكل',
            'galleryCTATitle'     => 'أريد مشروعاً مثل هذا',
            'galleryCTADesc'      => 'تواصل معنا الآن وسنقدم لك عرض سعر مجاني في نفس اليوم.',
            'galleryCTABtn'       => 'اطلب عرض سعر مجاني',
            // Portfolio
            'portfolioBadge'       => 'معرض أعمالنا',
            'portfolioPageTitle'   => 'مشاريع',
            'portfolioPageHighlight'=> 'مميزة',
            'portfolioPageDesc'    => 'تصفح أرشيفنا المليء بالحملات الإعلانية الناجحة والمشاريع الإبداعية.',
            'clientLabel'          => 'العميل:',
            'noProjects'           => 'لا توجد مشاريع',
        ],
        'en' => [
            // Nav
            'home'          => 'Home',
            'about'         => 'About',
            'portfolio'     => 'Portfolio',
            'services'      => 'Services',
            'gallery'       => 'Gallery',
            'contact'       => 'Contact',
            'startProject'  => 'Start Project',
            'exploreWork'   => 'Explore Our Work',
            'contactUs'     => 'Contact Us',
            'contactInfoTitle' => 'Contact Information',
            // Stats
            'statsProjects' => 'Successful Projects',
            'statsClients'  => 'Satisfied Clients',
            'statsYears'    => 'Years Experience',
            'statsTeam'     => 'Trusted Brands',
            // Why us
            'whyUsTitle'    => 'Why Choose Flex?',
            'whyUsSubtitle' => 'We combine unlimited creativity with deep expertise in the Saudi market to deliver results that exceed expectations.',
            'competitiveBadge' => 'Our Competitive Edge',
            'whyF1T' => '11+ Years of Experience',
            'whyF1D' => 'Since 2015, working with companies across the Eastern Region, Riyadh, and all of Saudi Arabia.',
            'whyF2T' => 'Out-of-the-Box Ideas',
            'whyF2D' => 'We challenge conventional templates and invent advertising solutions never seen before.',
            'whyF3T' => 'Always On Time',
            'whyF3D' => 'We commit to deadlines without compromising quality or attention to detail.',
            'whyF4T' => 'Material Quality is Non-Negotiable',
            'whyF4D' => 'We select the finest printing materials, sign substrates, and finishes — every detail reflects your brand.',
            'whyF5T' => 'Design, Manufacture & Install',
            'whyF5D' => 'Every project phase under one roof — from the first design sketch to the final bolt on-site.',
            'whyF6T' => 'Real On-Site Presence',
            'whyF6D' => 'Our team comes to you — we measure, plan, and personally supervise every installation.',
            // CTA
            'ctaTitle'   => 'Ready to Make Noise?',
            'ctaSubtitle'=> "Let's talk about your next project and how we can turn it into a success story.",
            'startNow'   => 'Get Started',
            // Services section
            'servicesTitle'    => 'What We Offer',
            'servicesSubtitle' => 'A comprehensive suite of advertising and creative services designed to elevate your brand and lead the competition.',
            'viewAll'          => 'View All Services',
            'portfolioTitle'   => 'Featured Work',
            'portfolioSubtitle'=> "Some of the projects we're proud of. We put our magic touch into every detail.",
            'viewGallery'      => 'Browse Full Gallery',
            // About page
            'aboutBadge'    => 'Flex Story',
            'aboutHero1'    => 'Who Are We?',
            'aboutHero2'    => 'An Agency That Makes a Difference',
            'aboutHeroDesc' => 'Flex Agency was founded in 2015 in Dammam. Over the years, the agency has achieved significant growth in its work, activities, and services across all advertising sectors.',
            'storyTitle'     => 'A Success Story',
            'storyHighlight' => 'Real',
            'storyP1' => 'Flex Advertising Agency was founded in 2015 in Dammam, Saudi Arabia. The agency currently covers all regions of the Kingdom.',
            'storyP2' => 'The agency has executed numerous projects and advertising campaigns, organized festivals and events in the Eastern Region and beyond. Thanks to tireless efforts from its team, Flex achieved significant milestones in record time.',
            'storyP3' => 'It has left a distinctive mark with its clients through high values — honesty, integrity, and the highest quality standards in all projects.',
            'statFounded' => 'Year Founded',
            'statProjects'=> 'Completed Projects',
            'statClients' => 'Satisfied Clients',
            'statRegions' => 'Covered Regions',
            'statYears'   => 'Years Experience',
            'visionLabel' => 'OUR VISION',
            'visionTitle' => 'Our Vision',
            'visionText'  => 'Our vision at Flex is to be one of the leading agencies in providing innovative marketing solutions and advertising services, pioneering modern printing services with advanced, high-quality technologies.',
            'missionLabel'=> 'OUR MISSION',
            'missionTitle'=> 'Our Mission',
            'missionText' => 'We always strive at Flex to deliver the best quality in services and advertising to achieve the highest levels of client satisfaction using the latest and most innovative printing equipment.',
            'valuesTitle'    => 'Our Values',
            'valuesHighlight'=> 'Core',
            'valuesSubtitle' => 'These values are the foundation of our policy in serving our clients.',
            'v1T' => 'Integrity & Honesty',           'v1D' => 'We commit to full transparency in all our dealings with clients and partners.',
            'v2T' => 'Highest Quality Standards',     'v2D' => 'We uphold the highest quality standards in all work without compromise.',
            'v3T' => 'On-Time Delivery',               'v3D' => 'We honor agreed timelines and always strive to deliver on schedule.',
            'v4T' => 'Client Satisfaction First',      'v4D' => "We place our clients' satisfaction at the top of our priorities.",
            'v5T' => 'Continuous Innovation',          'v5D' => 'We keep pace with the latest technologies and global trends in advertising.',
            'v6T' => 'Full Coverage',                  'v6D' => 'We cover all regions of Saudi Arabia to serve every client.',
            'officesTitle'    => 'Our Offices',
            'officesHighlight'=> 'in Saudi Arabia',
            'office1City'  => 'Dammam', 'office1Desc' => 'Headquarters — Eastern Region, Saudi Arabia', 'office1Badge' => 'Headquarters',
            'office2City'  => 'Riyadh', 'office2Desc' => 'Riyadh Office — Central Region, Saudi Arabia', 'office2Badge' => 'Branch',
            'aboutCtaTitle'=> 'Ready to Work With Us?',
            'aboutCtaDesc' => "Let's discuss your next project and provide an advertising solution that achieves your goals.",
            'aboutCtaBtn'  => 'Contact Us',
            // Services page
            'servicesBadge'       => 'What We Offer',
            'servicesPageTitle'   => 'Our Services',
            'servicesPageHighlight'=> 'Creative',
            'servicesPageDesc'    => 'Flex offers a comprehensive suite of advertising, printing, and manufacturing services using the latest technologies.',
            'workshopTitle'       => 'Manufacturing Workshop',
            'workshopHighlight'   => 'Integrated',
            'workshopDesc'        => 'We manufacture all types of advertising signage with the highest quality and latest technologies.',
            'workshopBtn'         => 'Request a Quote',
            'w1' => 'Flex Face Signs',    'w2' => 'Unipole Signs',     'w3' => '3D Letter Signs',
            'w4' => 'Cladding Facades',  'w5' => 'Banner Signs',       'w6' => 'Car Stickers',
            'servicesCtaTitle'=> 'Ready for the Next Step?',
            'servicesCtaDesc' => "Let's work together to turn your ideas into a campaign the market will talk about.",
            'servicesCtaBtn'  => 'Request a Quote',
            // Contact
            'contactBadge'    => "We're Here to Listen",
            'contactHero1'    => 'Contact',
            'contactHero2'    => 'Us',
            'contactHeroDesc' => 'Share your vision and we will turn it into a reality that exceeds your expectations. Our team is ready to answer your inquiries.',
            'contactDammam'       => 'Dammam — Headquarters',
            'contactDammamRegion' => 'Eastern Region, Saudi Arabia',
            'contactRiyadh'       => 'Riyadh — Branch',
            'contactRiyadhRegion' => 'Central Region, Saudi Arabia',
            'contactHoursDays'    => 'Sunday — Thursday',
            'contactHoursTime'    => '9:00 AM — 6:00 PM',
            'formTitle'   => 'Send Us a Message',
            'formName'    => 'Full Name',
            'formPhone'   => 'Phone Number',
            'formEmail'   => 'Email Address',
            'formOptional'=> '(optional)',
            'formMessage' => 'Project Details or Inquiry',
            'formNamePh'  => 'Enter your name',
            'formMsgPh'   => 'Tell us about your project or what you need...',
            'formSubmit'  => 'Send Message',
            'formSending' => 'Sending...',
            'formSuccess' => 'Message sent! We will contact you shortly.',
            'formError'   => 'An error occurred, please try again.',
            'sendAnother' => 'Send Another Message',
            // Footer
            'footerBio'          => 'Flex Advertising Agency was founded in 2015 in Dammam, Saudi Arabia, covering all regions of the Kingdom with the highest quality and professionalism.',
            'footerQuickLinks'   => 'Quick Links',
            'footerServicesTitle'=> 'Our Services',
            'footerContactTitle' => 'Contact Us',
            'footerCopyright'    => 'Flex for Advertising — All Rights Reserved.',
            'fs1' => 'Digital Printing',   'fs2' => 'Corporate Identity', 'fs3' => 'Event Management',
            'fs4' => '3D Design',          'fs5' => 'Car Stickers',       'fs6' => 'Manufacturing Workshop',
            'fs7' => 'Sign Board Manufacturing', 'fs8' => 'Professional Display Stands',
            // Gallery
            'galleryPageTitle'    => 'Project',
            'galleryPageHighlight'=> 'Gallery',
            'galleryPageDesc'     => 'Real photos from our executed projects — printing, manufacturing, events, corporate identities and more.',
            'filterAll'           => 'All',
            'galleryCTATitle'     => 'I Want a Project Like This',
            'galleryCTADesc'      => 'Contact us now and we will provide a free quote the same day.',
            'galleryCTABtn'       => 'Request Free Quote',
            // Portfolio
            'portfolioBadge'        => 'Our Portfolio',
            'portfolioPageTitle'    => 'Featured',
            'portfolioPageHighlight'=> 'Projects',
            'portfolioPageDesc'     => 'Browse our archive of successful advertising campaigns and creative projects.',
            'clientLabel'           => 'Client:',
            'noProjects'            => 'No Projects Found',
        ],
    ];
}
